#include<iostream>
using namespace std;
int main ()
{
    float BASIC_SALARY , PERCENTAGE_OF_ALLOWANCES , PERCENTAGE_OF_DEDUCTIONS , NET_SALARY;
    cout<<"Enter the BASIC_SALARY"<<endl<<"Enter the PERCENTAGE_OF_ALLOWANCES"<<endl<<"Enter the PERCENTAGE_OF_DEDUCTIONS"<<endl;
    cin>>BASIC_SALARY>>PERCENTAGE_OF_ALLOWANCES>>PERCENTAGE_OF_DEDUCTIONS;
    NET_SALARY=BASIC_SALARY+(BASIC_SALARY*PERCENTAGE_OF_ALLOWANCES/100)-(BASIC_SALARY*PERCENTAGE_OF_DEDUCTIONS/100);
    cout<<"YOUR NET SALARY IS"<<"   "<<NET_SALARY;
    return 0;
}